spring:
  application:
    name: cloud.computing.inventory

  datasource:
    url: jdbc:mysql://${MYSQL_HOSTNAME}:3306/${MYSQL_DATABASE}
    password: ${MYSQL_PASSWORD}
    username: ${MYSQL_USERNAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: never

# restock random products each 5 minutes
inventory:
  restock:
    enabled: ${RESTOCK_ENABLE:true}
    products-number: ${RESTOCK_PRODUCT_NUMBER:20}
    rate-ms: ${RESTOCK_FREQUENCY:300000}